# ==========================================
# Configurator stage
# ==========================================
FROM alpine:latest AS configurator

ARG CC_VERSION

COPY oneAPI.json /

RUN apk add jq \
 && DPCPP_NVIDIA_URL=$(jq ".\"${CC_VERSION}\".DPCPP_NVIDIA_URL" /oneAPI.json) \
 && DPCPP_NVIDIA_URL_CHECKSUM_SHA256=$(jq ".\"${CC_VERSION}\".DPCPP_NVIDIA_URL_CHECKSUM_SHA256" /oneAPI.json) \
 && echo -e "\
export DPCPP_NVIDIA_URL=${DPCPP_NVIDIA_URL}\n\
export DPCPP_NVIDIA_URL_CHECKSUM_SHA256=${DPCPP_NVIDIA_URL_CHECKSUM_SHA256}\n" >> /oneAPI.env

# ==========================================
# rhel + dpcpp + cuda
# ==========================================
FROM base AS rhel

ARG CC_VERSION

COPY docker-entrypoint.d/99-oneapi-setvars.sh /docker-entrypoint.d/
COPY rhel/oneAPI.repo /etc/yum.repos.d/
COPY rhel/cuda.repo /etc/yum.repos.d/
COPY --from=configurator /oneAPI.env /tmp/

RUN dnf -y install \
      cuda-minimal-build-12-1 \
      "intel-oneapi-compiler-dpcpp-cpp-${CC_VERSION}" \
 # NVIDIA plugin for dpcpp
 && . /tmp/oneAPI.env \
 && wget -qO /tmp/oneapi-cuda-install.sh "${DPCPP_NVIDIA_URL}" \
 && echo "${DPCPP_NVIDIA_URL_CHECKSUM_SHA256} /tmp/oneapi-cuda-install.sh" | sha256sum -c - \
 && chmod +x /tmp/oneapi-cuda-install.sh \
 && /tmp/oneapi-cuda-install.sh --oneapi-root /opt/intel/oneapi \
 # cleanup
 && dnf -y clean all \
 && rm -fr /tmp/*
