FROM base AS rhel

ARG CC_VERSION

COPY "docker-entrypoint.d/00-rhel-gcc-toolset-${CC_VERSION}.sh" /docker-entrypoint.d/

RUN dnf -y install \
      "gcc-toolset-${CC_VERSION}" \
      "gcc-toolset-${CC_VERSION}-libasan-devel"  \
      "gcc-toolset-${CC_VERSION}-liblsan-devel"  \
      "gcc-toolset-${CC_VERSION}-libtsan-devel"  \
      "gcc-toolset-${CC_VERSION}-libubsan-devel" \
 && dnf -y clean all

# ======================================================================
# RHEL ships gcc11 as the system's default compiler and not as a toolset,
# we need to specialize for it.
# ======================================================================
FROM base AS rhel-gcc11

RUN dnf -y install gcc g++ \
 && dnf -y clean all
