# ==========================================
# debian + clangXX
# ==========================================

FROM debian:trixie AS debian

ARG CC_VERSION=00

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends \
      wget \
      ca-certificates \
      ninja-build \
 && wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc \
 && echo "\
deb http://apt.llvm.org/trixie/ llvm-toolchain-trixie-${CC_VERSION} main\n\
deb-src http://apt.llvm.org/trixie/ llvm-toolchain-trixie-${CC_VERSION} main\n" >> /etc/apt/sources.list \
 && apt-get update -y \
 && apt-get install -y \
      "clang-${CC_VERSION}" \
      "clang-tools-${CC_VERSION}" \
      "clang-format-${CC_VERSION}" \
      "clang-tidy-${CC_VERSION}" \
      "libclang-rt-${CC_VERSION}-dev" \
      "libc++-${CC_VERSION}-dev" \
      "libc++abi-${CC_VERSION}-dev" \
      "lld-${CC_VERSION}" \
      "llvm-${CC_VERSION}-linker-tools" \
 && update-alternatives \
      --install /usr/bin/clang           clang           "/usr/bin/clang-${CC_VERSION}" 200 \
      --slave   /usr/bin/clang++         clang++         "/usr/bin/clang++-${CC_VERSION}" \
      --slave   /usr/bin/lld             lld             "/usr/bin/lld-${CC_VERSION}" \
      --slave   /usr/bin/clang-tidy      clang-tidy      "/usr/bin/clang-tidy-${CC_VERSION}" \
      --slave   /usr/bin/clang-format    clang-format    "/usr/bin/clang-format-${CC_VERSION}" \
      --slave   /usr/bin/llvm-symbolizer llvm-symbolizer "/usr/bin/llvm-symbolizer-${CC_VERSION}" \
 && rm -rf /var/lib/apt/lists/*
