# ==========================================
# Configurator stage
# ==========================================
FROM alpine:latest AS configurator

ARG CC_VERSION

COPY oneAPI.json /oneAPI.json

RUN apk add jq \
 && DPCPP_NVIDIA_URL=$(jq ".\"${CC_VERSION}\".DPCPP_NVIDIA_URL" /oneAPI.json) \
 && DPCPP_NVIDIA_URL_CHECKSUM_SHA256=$(jq ".\"${CC_VERSION}\".DPCPP_NVIDIA_URL_CHECKSUM_SHA256" /oneAPI.json) \
 && echo -e "\
export DPCPP_NVIDIA_URL=${DPCPP_NVIDIA_URL}\n\
export DPCPP_NVIDIA_URL_CHECKSUM_SHA256=${DPCPP_NVIDIA_URL_CHECKSUM_SHA256}\n" >> /oneAPI.env

# ==========================================
# RHEL + dpcpp + cuda
# ==========================================
FROM registry.access.redhat.com/ubi9/ubi:9.8-1779808651 AS rhel

ARG CC_VERSION

COPY docker-entrypoint.d/99-oneapi-setvars.sh /docker-entrypoint.d/
COPY oneAPI.repo.rhel /etc/yum.repos.d/oneAPI.repo
COPY cuda.repo.rhel /etc/yum.repos.d/cuda.repo
COPY --from=configurator /oneAPI.env /oneAPI.env

RUN dnf -y install \
      procps-ng \
      wget \
      tar \
      ninja-build \
      cmake \
      cuda-minimal-build-12-1 \
      "intel-oneapi-mkl-classic-devel-${CC_VERSION}" \
      "intel-oneapi-compiler-dpcpp-cpp-${CC_VERSION}" \
 # NVIDIA plugin for dpcpp
 && . /oneAPI.env \
 && wget -qO /tmp/oneapi-cuda-install.sh "${DPCPP_NVIDIA_URL}" \
 && echo "${DPCPP_NVIDIA_URL_CHECKSUM_SHA256} /tmp/oneapi-cuda-install.sh" | sha256sum -c - \
 && chmod +x /tmp/oneapi-cuda-install.sh \
 && /tmp/oneapi-cuda-install.sh --oneapi-root /opt/intel/oneapi \
 # cleanup
 && dnf -y clean all \
 && rm -fr /tmp/*

# COPY entrypoint.sh /entrypoint.sh
# ENTRYPOINT ["/entrypoint.sh"]
