FROM base
ARG BOOST_URL
ARG BOOST_URL_CHECKSUM_SHA256
ARG BOOST_BUILD_TOOLSET=gcc
ARG BOOST_BUILD_CXXSTD=20

# Note: don't install additional toolchains, 'base' provides the correct one.

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends \
      aria2 tar ca-certificates \
 && aria2c --checksum=sha-256="${BOOST_URL_CHECKSUM_SHA256}" -d /tmp -o boost.archive "${BOOST_URL}" \
 && mkdir -p /tmp/boost.src \
 && tar xf /tmp/boost.archive -C /tmp/boost.src/ --strip-components 1 \
 && cd /tmp/boost.src \
 && ./bootstrap.sh --with-toolset=gcc --with-libraries=graph,program_options \
 && ./b2 cxxstd="${BOOST_BUILD_CXXSTD}" toolset="${BOOST_BUILD_TOOLSET}" --with-graph --with-program_options stage \
 && ./b2 cxxstd="${BOOST_BUILD_CXXSTD}" toolset="${BOOST_BUILD_TOOLSET}" --with-graph --with-program_options --prefix=/opt/boost install \
 && rm -rf /tmp/*
