ARG GCC_VERSION=00

# ==========================================
# debian + gccXX (official image) 
# ==========================================

FROM gcc:${GCC_VERSION} AS ubuntu

ARG GCC_VERSION

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends \
      wget \
      tar \
      ca-certificates

# ==========================================
# RHEL 9 + gccXX (from official toolsets)
# ==========================================
FROM registry.access.redhat.com/ubi9/ubi AS rhel

ARG GCC_VERSION

RUN dnf -y update \
 && dnf install -y \
      wget \
      tar \
      gcc-toolset-${GCC_VERSION} \
      gcc-toolset-${GCC_VERSION}-libasan-devel  \
      gcc-toolset-${GCC_VERSION}-liblsan-devel  \
      gcc-toolset-${GCC_VERSION}-libtsan-devel  \
      gcc-toolset-${GCC_VERSION}-libubsan-devel \
 && dnf clean all
