# ==========================================
# downloader: common stage to download stuff
# ==========================================
FROM ubuntu:24.04 AS downloader

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends \
      aria2 \
      ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# ==========================================
# mkl-installer: installs mkl to /opt/intel/mkl
# ==========================================
FROM downloader AS mkl-installer

ARG MKL_URL="https://registrationcenter-download.intel.com/akdlm/IRC_NAS/db60f483-f02e-4f7e-9bcd-5e01dba97444/intel-onemkl-2026.0.0.909_offline.sh"
ARG MKL_URL_CHECKSUM_SHA256="f63fd6ce3a374993caa0482fec0a3b9f2c312beeabff82009ab51fca90c97225"

RUN aria2c --checksum="sha-256=${MKL_URL_CHECKSUM_SHA256}" -d /tmp -o mkl-install.x "${MKL_URL}" \
 && chmod +x /tmp/mkl-install.x \
 && /tmp/mkl-install.x -a --silent --eula accept --install-dir /opt/intel/mkl \
 && rm -rf /tmp/*

# ==========================================
# cmake-installer: installs cmake to /usr
# ==========================================
FROM downloader AS cmake-installer

ARG CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6-Linux-x86_64.sh"
ARG CMAKE_URL_CHECKSUM_SHA256="518c76bd18cc4ca5faab891db69b1289dc1bf134f394f0983a19576711b95210" 

RUN aria2c --checksum="sha-256=${CMAKE_URL_CHECKSUM_SHA256}" -d /tmp -o cmake-install.x "${CMAKE_URL}" \
 && chmod +x /tmp/cmake-install.x \
 && mkdir -p /opt/cmake \
 && /tmp/cmake-install.x --prefix=/opt/cmake --skip-license \
 && rm -rf /tmp/*

# ==========================================
# final stage
# ==========================================
FROM base

COPY --from=boost-builder /opt/boost/ /usr/
COPY --from=cmake-installer /opt/cmake/ /usr/
COPY --from=mkl-installer /opt/intel /opt/intel

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
