# ==========================================
# Downloader stage
# ==========================================
FROM alpine:latest AS downloader

ARG BOOST_URL
ARG BOOST_URL_CHECKSUM_SHA256

RUN apk add aria2 \
 && aria2c --checksum="sha-256=${BOOST_URL_CHECKSUM_SHA256}" -d /tmp -o boost.archive "${BOOST_URL}" \
 && mkdir -p /opt/boost.src \
 && tar xf /tmp/boost.archive -C /opt/boost.src/ --strip-components 1 \
 && rm -fr /tmp/*

# ==========================================
# Builder stage
# ==========================================

FROM base
ARG BOOST_BUILD_TOOLSET=gcc
ARG BOOST_BUILD_CXXSTD=20

COPY --from=downloader /opt/boost.src /tmp/boost.src

RUN cd /tmp/boost.src \
 && ./bootstrap.sh --with-toolset="${BOOST_BUILD_TOOLSET}" --with-libraries=graph,program_options \
 && ./b2 cxxstd="${BOOST_BUILD_CXXSTD}" toolset="${BOOST_BUILD_TOOLSET}" --with-graph --with-program_options stage \
 && ./b2 cxxstd="${BOOST_BUILD_CXXSTD}" toolset="${BOOST_BUILD_TOOLSET}" --with-graph --with-program_options --prefix=/opt/boost install \
 && rm -rf /tmp/*
