ARG CC_VERSION=00

# ==========================================
# debian + gccXX (official image) 
# ==========================================

FROM gcc:${CC_VERSION} AS debian

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends \
      wget \
      tar \
      ninja-build \
      cmake \
      ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# ==========================================
# RHEL 9 + gccXX (from official toolsets)
# ==========================================
FROM registry.access.redhat.com/ubi9/ubi:9.8-1779808651 AS rhel

ARG CC_VERSION

RUN dnf -y install \
      procps-ng \
      wget \
      tar \
      ninja-build \
      cmake \
      "gcc-toolset-${CC_VERSION}" \
      "gcc-toolset-${CC_VERSION}-libasan-devel"  \
      "gcc-toolset-${CC_VERSION}-liblsan-devel"  \
      "gcc-toolset-${CC_VERSION}-libtsan-devel"  \
      "gcc-toolset-${CC_VERSION}-libubsan-devel" \
 && dnf -y clean all
