# ==========================================
# debian + gccXX (official image) 
# ==========================================
ARG GCC_VERSION=00

FROM gcc:${GCC_VERSION} AS ubuntu

# ==========================================
# RHEL 9 + gccXX (from official toolsets)
# ==========================================
FROM registry.access.redhat.com/ubi9/ubi AS rhel

ARG GCC_VERSION=00

RUN dnf -y update \
 && dnf install -y \
      gcc-toolset-${GCC_VERSION} \
      gcc-toolset-${GCC_VERSION}-libasan-devel  \
      gcc-toolset-${GCC_VERSION}-liblsan-devel  \
      gcc-toolset-${GCC_VERSION}-libtsan-devel  \
      gcc-toolset-${GCC_VERSION}-libubsan-devel \
 && dnf clean all
