# ==========================================
# debian + gccXX (official image) 
# ==========================================
ARG CC_VERSION=00

FROM gcc:${CC_VERSION} AS debian

ARG ONEAPI_VERSION

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends \
      gpg \
      wget \
      ca-certificates \
 && wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor > /usr/share/keyrings/oneapi-archive-keyring.gpg \
 && echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" > /etc/apt/sources.list.d/oneAPI.list \
 && apt-get update -y \
 && apt-get install -y --no-install-recommends \
      procps \
      tar \
      ninja-build \
      cmake \
      "intel-oneapi-mkl-classic-devel-${ONEAPI_VERSION}" \
 && rm -rf /var/lib/apt/lists/*

# ==========================================
# RHEL 9 + gccXX (from official toolsets)
# ==========================================
FROM registry.access.redhat.com/ubi9/ubi:9.8-1779808651 AS rhel

ARG CC_VERSION
ARG ONEAPI_VERSION

COPY oneAPI.repo.rhel /etc/yum.repos.d/oneAPI.repo

RUN dnf -y install \
      procps-ng \
      wget \
      tar \
      ninja-build \
      cmake \
      "intel-oneapi-mkl-classic-devel-${ONEAPI_VERSION}" \
      "gcc-toolset-${CC_VERSION}" \
      "gcc-toolset-${CC_VERSION}-libasan-devel"  \
      "gcc-toolset-${CC_VERSION}-liblsan-devel"  \
      "gcc-toolset-${CC_VERSION}-libtsan-devel"  \
      "gcc-toolset-${CC_VERSION}-libubsan-devel" \
 && dnf -y clean all
