FROM base AS mkl-downloader-rhel

ARG MKL_URL
ARG MKL_URL_CHECKSUM_SHA256

RUN wget -O /tmp/mkl-install.x -q "${MKL_URL}" \
 && echo "${MKL_URL_CHECKSUM_SHA256} /tmp/mkl-install.x" | sha256sum --check - \
 && chmod +x /tmp/mkl-install.x \
 && /tmp/mkl-install.x -a --silent --eula accept --install-dir /opt/intel/mkl \
 && rm -rf /tmp/*

# intel-oneapi-mkl-devel
# intel-oneapi-mkl
# intel-oneapi-mkl-classic-devel
# intel-oneapi-mkl-classic
